[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log

[program:fastapi]
command=uvicorn api:app --host 0.0.0.0 --port 8000
directory=/app/api
autostart=true
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:streamlit]
command=streamlit run app.py --server.port=7860 --server.address=0.0.0.0
directory=/app/app
autostart=true
autorestart=true
startretries=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0